services:
  mysql:
    container_name: mysql-container
    image: mysql:8.3.0
    networks:
      - mynetwork
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_LOWER_CASE_TABLE_NAMES=0
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
  redis:
    container_name: redis-container
    image: redis:7.4
    networks:
      - mynetwork
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
  rabbitmq:
    container_name: rabbitmq-container
    image: rabbitmq:4.0-management
    networks:
      - mynetwork
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq # 持久化数据
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 123456
  meilisearch:
    image: getmeili/meilisearch:v1.10.2
    environment:
      - MEILI_ENV=development
    ports:
      - "7700:7700"
    volumes:
      - ./data/meili_data:/meili_data
  email-server:
    container_name: email-server-container
    image: crpi-os06t9qra24xdcv8.cn-beijing.personal.cr.aliyuncs.com/fudawei-namespace/email-server:1.0.0
    networks:
      - mynetwork
    depends_on:
      - rabbitmq
  log-server:
    container_name: log-server-container
    image: crpi-os06t9qra24xdcv8.cn-beijing.personal.cr.aliyuncs.com/fudawei-namespace/log-server:1.0.0
    networks:
      - mynetwork
    depends_on:
      - rabbitmq
      - mysql
networks:
  mynetwork:
    external: true